export default {
  VALIDATE_SCREEN: 'VALIDATE_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  ATTENDANCE_DETAIL_SCREEN: 'ATTENDANCE_DETAIL_SCREEN',
  ATTENDANCE_REPORT_SCREEN: 'ATTENDANCE_REPORT_SCREEN'
};
